paths:
  data_folder: "data/raw"
  file_names:
    - "workshop.txt"
    - "rerun.txt"
    - "overall.txt"
  faiss_index: "artifacts/faiss_product_index"

models:
  embedding: "text-embedding-3-small"
  llm: "gpt-3.5-turbo"

retriever:
  search_type: "similarity"
  k_value: 4
 
# Reference to prompt template file
prompt_config:
  template_name: "sales_support"
  version: "v1"

# Tools configuration
tools:
  enabled: true  # Master switch
  calculator:
    enabled: true
    tools: [multiply, calculate_expression, fibonacci, statistics]
  text_analyzer:
    enabled: true
    tools: [count_words, analyze_text]

# Guardrails configuration
guardrails:
  enabled: true
  
  # Input validation settings
  input_validation:
    enabled: true
    max_length: 1000
    min_length: 1
    check_prompt_injection: true
    prompt_injection_threshold: 0.8
    check_profanity: true
    profanity_severity: "warning"  # "warning" or "fail"
    allowed_languages: ["th", "en"]
  
  # Content safety settings
  content_safety:
    enabled: true
    toxicity_threshold: 0.7
    hate_speech_threshold: 0.8
    
  # PII detection settings
  pii_detection:
    enabled: true
    mask_pii: true
    fail_on_pii: false  # Set to true for stricter PII handling
    allowed_pii_types: []  # Add allowed PII types if needed
    
  # Output validation settings
  output_validation:
    enabled: true
    max_response_length: 2000
    min_response_length: 5
    check_relevance: true
    relevance_threshold: 0.6
    check_hallucination: true
    hallucination_threshold: 0.8